const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const model=require('../assets/js/issue-model.js'),sync=require('../assets/js/sync-model.js');
const state=()=>({read:{},completedAt:{},issueRead:{}});
const order=(id,items,publisher='DC')=>({id,title:id,publisher,sections:[{key:0,title:'Phase',items:items.map(e=>({companions:[],...e}))}]});
const a=order('batman',[{title:'Robin: Year One',details:'Reúne Robin: Year One #1-4.',companions:[{title:'Batman: King Tut’s Tomb',details:'Reúne Batman Confidential #26-28, The Brave And The Bold #164, 171, e Batman #353.'}]}]);
const b=order('other',[{title:'Batman Confidential (2007) #26-28'},{title:'Batman (1940) #353'},{title:'Robin: Year One'}]);
const idx=model.build([a,b]),king=idx.rows.get('batman:0:0:c0');
assert.equal(king.issues.length,6);assert.deepEqual(king.groups.map(g=>g.issues.map(i=>i.number)),[['26','27','28'],['164','171'],['353']]);assert.equal(king.complete,true);
assert.equal(idx.rows.get('batman:0:0').issues.length,4);assert.equal(idx.byIssue.get(king.issues[0].id).length,2);
const p=state();let result=model.mark(idx,p,[king.issues[0].id],true,'2026-10-08T12:00:00Z');assert.equal(result.view.status.get(king.key).done,1);assert.equal(result.view.status.get(king.key).read,false);assert.equal(result.view.status.get('other:0:0').done,1);assert.equal(result.view.status.get('batman:0:0').read,false);
model.mark(idx,p,['other:0:0'],true,'2026-10-08T12:00:00Z');assert.equal(model.view(idx,p).status.get(king.key).done,3);assert.equal(model.view(idx,p).read[king.key],undefined);
model.mark(idx,p,[king.key],true,'2026-10-08T12:00:00Z');assert.equal(model.view(idx,p).read['other:0:1'],true);assert.equal(model.view(idx,p).read['batman:0:0'],undefined);
model.mark(idx,p,[king.issues[0].id],false,'2026-10-08T12:00:00Z');assert.equal(model.view(idx,p).read[king.key],undefined);assert.equal(model.view(idx,p).read['other:0:0'],undefined);assert.equal(model.view(idx,p).status.get(king.key).done,5);assert.equal(model.view(idx,p).read['other:0:1'],true);
assert.doesNotThrow(()=>model.validate(p.issueRead));
console.log('PASS individual issue marking, partial collections, cross-list propagation and global unmarking without marking unrelated Robin story');
const legacy=state();legacy.read[king.key]=true;legacy.completedAt[king.key]='2025-01-01T12:00:00Z';const before=JSON.stringify(legacy),derived=model.view(idx,legacy);assert.equal(JSON.stringify(legacy),before);assert.equal(derived.read['other:0:0'],true);assert.equal(derived.marks.get(king.issues[0].id).date,legacy.completedAt[king.key]);
model.mark(idx,legacy,[king.issues[0].id],false,'2026-10-08T12:00:00Z');assert.equal(model.view(idx,legacy).status.get(king.key).done,5);assert.equal(JSON.parse(legacy.issueRead[king.issues[1].id]).date,'2025-01-01T12:00:00Z');
const unknown=state();unknown.read[king.key]=true;model.mark(idx,unknown,[king.issues[0].id],false,'2026-10-08T12:00:00Z');assert.equal(JSON.parse(unknown.issueRead[king.issues[1].id]).date,'');
const cleared=state();model.mark(idx,cleared,[king.key],true,'2026-10-08T12:00:00Z');delete cleared.completedAt[king.key];assert.equal(model.view(idx,cleared).completedAt[king.key],undefined);model.mark(idx,cleared,[king.key],true,'2026-10-09T12:00:00Z');assert.equal(model.view(idx,cleared).completedAt[king.key],undefined);
const roundtrip=sync.fromRemote(sync.diff({},legacy).constructor===Object?Object.fromEntries(sync.fields.map(f=>[f,Object.fromEntries(Object.entries(legacy[f]||{}).map(([k,v])=>[sync.encode(k),v]))])):{});assert.deepEqual(roundtrip.issueRead,legacy.issueRead);
console.log('PASS old saves keep original keys and known/unknown dates; issue tombstones survive JSON and sync encoding');
const variants=model.build([order('variants',[{title:'Batman (1940) #1'},{title:'Batman (2011) #1'},{title:'Batman Vol. 2 #1'},{title:'Batman #1'},{title:'Batman (2016) #1'},{title:'Batman Annual (2016) #1'}]),order('elsewhere',[{title:'Batman #1'}]),order('marvel',[{title:'Captain Marvel (2012) #1'}],'Marvel'),order('dc',[{title:'Captain Marvel (2012) #1'}])]);
const v=[...variants.rows.values()];assert.equal(v[1].issues[0].id,v[2].issues[0].id);assert.equal(new Set([v[0],v[1],v[3],v[4],v[5],v[6],v[7],v[8]].map(r=>r.issues[0].id)).size,8);
assert.equal(model.parse({title:'Note',details:'Leia Batman #1 depois.'},{key:'a',orderId:'x',publisher:'DC'}).groups.length,0);
assert.equal(model.parse({title:'Partial',details:'Reúne histórias de Batman (2011) #1-6.'},{key:'a',orderId:'x',publisher:'DC'}).groups.length,0);
assert.equal(model.parse({title:'Partial',details:'Reúne Batman (2011) #1 (história B), Detective Comics #600.'},{key:'a',orderId:'x',publisher:'DC'}).groups.length,0);
const parts=model.parse({title:'Range',details:'Reúne Batman (1940) #232, #235, #240, and #242-244; Detective Comics (1937) #500.'},{key:'a',orderId:'x',publisher:'DC'});assert.deepEqual(parts.groups[0].issues.map(i=>i.number),['232','235','240','242','243','244']);assert.equal(parts.groups.length,2);
const contextForParse={key:'a',orderId:'x',publisher:'DC'};
assert.equal(model.parse({title:'The Cat and the Bat',details:'(2008) Reúne Batman Confidential #17-#21. Batgirl conhece Catwoman.'},contextForParse).groups[0].issues.length,5);
assert.equal(model.parse({title:'The Neighborhood',details:'Detective Comics #1034-1039'},contextForParse).groups[0].issues.length,6);
assert.equal(model.parse({title:'Batman: Gotham After Midnight',details:'Reúne Batman: Gotham After Midnight #1-12.'},contextForParse).groups[0].issues.length,12);
const half=model.parse({title:'Batman (1940) #½'},{key:'half',publisher:'DC'}).groups[0].issues[0];assert.ok(half.id.endsWith(':half'));assert.doesNotThrow(()=>model.validate({[half.id]:'{"read":true,"date":""}'}));
const custom=model.build([{...order('personal-abc',[{key:'one',title:'Batman Confidential (2007) #26'}],'Minhas listas'),personal:true,family:'Comics'},b]);assert.equal(custom.rows.get('personal-abc:0:one').issues[0].id,king.issues[0].id);
assert.equal(model.numbersFor('1-1000000'),null);assert.deepEqual(model.numbersFor('26–28, 30 & 32'),['26','27','28','30','32']);
for(const value of ['{}','{"read":"yes","date":""}','{"read":false,"date":"2026-01-01"}'])assert.throws(()=>model.validate({'issue:dc:batman:y1940:1':value}));
console.log('PASS relaunches, annuals, publishers, incomplete references and unresolved versions are kept separate');
const context={window:{}};const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,file]of html.matchAll(/src="(assets\/data\/[^?]+)\?/g))vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const catalogue=[...context.window.COMIC_ORDERS,...context.window.EXPANDED_ORDERS].map(o=>({...o,publisher:o.publisher||(/spider-man/i.test(o.title)?'Marvel':'DC')}));
const original=JSON.stringify(catalogue),index=model.build(catalogue);assert.equal(JSON.stringify(catalogue),original);assert.equal(index.rows.size,5696);const marked=state();for(const row of index.rows.values()){if(row.issues.length){model.validate(Object.fromEntries(row.issues.map(i=>[i.id,JSON.stringify({read:true,date:''})])));}}
const sample=[...index.rows.values()].filter(r=>/^(Robin: Year One|JLA: Year One|Batman: King Tut[’']s Tomb)$/.test(r.title));assert.ok(sample.every(r=>r.issues.length>0));
console.log(JSON.stringify({rows:index.rows.size,detailed:[...index.rows.values()].filter(r=>r.issues.length).length,linked:[...index.byIssue].filter(([id,keys])=>id.startsWith('issue:')&&keys.length>1).length,unknown:[...index.rows.values()].filter(r=>!r.issues.length).length}));
console.log('PASS all 109 catalogues audited without changing source IDs/order; numbered references validated');
