const assert=require('node:assert/strict');
const model=require('../assets/js/reading-model.js'),personal=require('../assets/js/personal-library.js');
const {randomUUID}=require('node:crypto');
const progress={read:{parent:true,child:true,old:true},completedAt:{child:'2026-09-29T12:00:00Z'},notes:{child:'=DANGEROUS()'},ratings:{child:5}};
const entries=[{key:'parent',hasCompanions:true},{key:'child',title:'Volume "1"',orderTitle:'Teste'},{key:'old',title:'Leitura antiga'}];
const history=model.history(entries,progress);
assert.equal(history.length,2);assert.equal(history[0].rating,5);assert.equal(history[1].date,'');
assert.equal(history.filter(row=>model.monthOf(row.date)==='2026-09').length,1);
delete progress.read.child;assert.equal(model.history(entries,progress).length,1);
for(const invalid of [0,6,1.5,'5',null])assert.throws(()=>model.validateMap({item:invalid},'ratings'));
for(const invalid of [0,10001,1.2,'20'])assert.throws(()=>model.validateMap({'2026-09':invalid},'goals'));
assert.throws(()=>model.validateMap({'2026-00':10},'goals'));
assert.throws(()=>model.validateMap(JSON.parse('{"__proto__":5}'),'ratings'));
const csv=model.csv(history);assert.ok(csv.includes('"Volume ""1"""'));assert.ok(csv.includes("'=DANGEROUS()"));
const id='personal-'+randomUUID(),item='item-'+randomUUID(),list=personal.serialize({id,title:'Teste',kind:'manga',items:[{id:item,title:'Volume 1'}]});
const trash={list,deletedAt:'2026-09-29T12:00:00Z',notes:{'batman:0:0':'cross-list'}};
assert.throws(()=>model.parseTrash(JSON.stringify(trash),id,personal),/outra lista/);
trash.notes={[`${id}:personal:${item}`]:'safe'};assert.doesNotThrow(()=>model.parseTrash(JSON.stringify(trash),id,personal));
assert.throws(()=>model.parseTrash(JSON.stringify({...trash,deletedAt:'bad'}),id,personal));
console.log('PASS diary avoids counting arc headings twice, preserves unknown dates, validates ratings/goals/trash and escapes CSV formula cells');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../assets/js/app.js'),'utf8');
const context={isValidDate:value=>typeof value==='string'&&Number.isFinite(Date.parse(value))};vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  function ensureCompletionDates('),source.indexOf('  function load(')),context);
const old={read:{unknown:true,known:true},completedAt:{known:'2026-08-22T12:00:00Z',unread:'2026-09-29T12:00:00Z'}};
context.ensureCompletionDates(old);assert.equal(old.completedAt.unknown,undefined);assert.equal(old.completedAt.known,'2026-08-22T12:00:00Z');assert.equal(old.completedAt.unread,undefined);
console.log('PASS backup normalization preserves unknown dates instead of inventing activity');
