const assert=require('node:assert/strict');
const model=require('../assets/js/reading-model.js'),personal=require('../assets/js/personal-library.js');
const {randomUUID}=require('node:crypto');
const progress={read:{parent:true,child:true,old:true},completedAt:{child:'2026-09-29T12:00:00Z'},notes:{child:'=DANGEROUS()'},ratings:{child:5}};
const entries=[{key:'parent',hasCompanions:true},{key:'child',title:'Volume "1"',orderTitle:'Teste'},{key:'old',title:'Leitura antiga'}];
const history=model.history(entries,progress);
assert.equal(history.length,2);assert.equal(history[0].rating,5);assert.equal(history[1].date,'');
assert.equal(history.filter(row=>model.monthOf(row.date)==='2026-09').length,1);
delete progress.read.child;assert.equal(model.history(entries,progress).length,1);
for(const invalid of [0,6,1.5,'5',null])assert.throws(()=>model.validateMap({item:invalid},'ratings'));
for(const invalid of [0,10001,1.2,'20'])assert.throws(()=>model.validateMap({'2026-09':invalid},'goals'));
assert.throws(()=>model.validateMap({'2026-00':10},'goals'));
assert.throws(()=>model.validateMap(JSON.parse('{"__proto__":5}'),'ratings'));
const csv=model.csv(history);assert.ok(csv.includes('"Volume ""1"""'));assert.ok(csv.includes("'=DANGEROUS()"));
const id='personal-'+randomUUID(),item='item-'+randomUUID(),list=personal.serialize({id,title:'Teste',kind:'manga',items:[{id:item,title:'Volume 1'}]});
const trash={list,deletedAt:'2026-09-29T12:00:00Z',notes:{'batman:0:0':'cross-list'}};
assert.throws(()=>model.parseTrash(JSON.stringify(trash),id,personal),/outra lista/);
trash.notes={[`${id}:personal:${item}`]:'safe'};assert.doesNotThrow(()=>model.parseTrash(JSON.stringify(trash),id,personal));
assert.throws(()=>model.parseTrash(JSON.stringify({...trash,deletedAt:'bad'}),id,personal));
console.log('PASS diary avoids counting arc headings twice, preserves unknown dates, validates ratings/goals/trash and escapes CSV formula cells');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../assets/js/app.js'),'utf8');
const context={isValidDate:value=>typeof value==='string'&&Number.isFinite(Date.parse(value))};vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  function ensureCompletionDates('),source.indexOf('  function load(')),context);
const old={read:{unknown:true,known:true},completedAt:{known:'2026-08-22T12:00:00Z',unread:'2026-09-29T12:00:00Z'}};
context.ensureCompletionDates(old);assert.equal(old.completedAt.unknown,undefined);assert.equal(old.completedAt.known,'2026-08-22T12:00:00Z');assert.equal(old.completedAt.unread,undefined);
console.log('PASS backup normalization preserves unknown dates instead of inventing activity');
for(const value of ['[]',JSON.stringify(['suspense','mangás'])])assert.doesNotThrow(()=>model.parseTags(value));
for(const value of ['null','{}','[1]','["","a"]','["a","a"]',JSON.stringify(['x'.repeat(31)]),JSON.stringify(Array(11).fill('x'))])assert.throws(()=>model.parseTags(value));
const repeat={key:'child',date:'2026-09-29T12:00:00Z',rating:4,note:'Releitura'};
for(const invalid of [{...repeat,rating:6},{...repeat,date:'invalid'},{...repeat,note:8},{...repeat,profile:'leak'}])assert.throws(()=>model.parseSession(JSON.stringify(invalid)));
progress.sessions={one:JSON.stringify(repeat)};assert.equal(model.history(entries,progress).filter(r=>r.sessionId).length,1);assert.equal(model.history(entries,progress).find(r=>r.sessionId).note,'Releitura');
const catalogue=[{key:'a',title:'Batman collection',details:'Batman #520–530, 550 & 560-562',orderTitle:'Batman'}, {key:'b',title:'Different collection',details:'Detective Comics #515-526; Batman #349-359',orderTitle:'Batman'}, {key:'c',title:'Batman (2016) #526',orderTitle:'Another list'}, {key:'d',title:'Caçador de Marte #1',orderTitle:'JLA'}];
assert.deepEqual(model.search(catalogue,'Batman #526').map(r=>r.key),['a','c']);assert.deepEqual(model.search(catalogue,'Batman #561').map(r=>r.key),['a']);assert.deepEqual(model.search(catalogue,'Batman #55'),[]);assert.deepEqual(model.search(catalogue,'cacador marte').map(r=>r.key),['d']);assert.deepEqual(model.search(catalogue,' '),[]);
console.log('PASS reread validation, private tags and issue search distinguish series and support ranges');
